{
 "title": "load",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"hostname\""
   }
  ]
 },
 "panels": [
  {
   "title": "load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "load" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "load1" }
     ]
    },
    {
     "alias": "5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "load" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "load5" }
     ]
    },
    {
     "alias": "15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "load" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "load15" }
     ]
    }
   ]
  },
  {
   "title": "mem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "mem" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "USED" }
     ]
    }
   ]
  },
  {
   "title": "latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "dummy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "latency" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "latency" }
     ]
    }
   ]
  },
  {
   "title": "checks/m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "icinga",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "icinga" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "active_service_checks_1min" }
     ]
    }
   ]
  }
 ]
}